import { Component } from '@angular/core';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.css'],
})
export class SearchComponent {
  districts = [
    { id: 1, name: 'Aniołki' },
    { id: 2, name: 'Brętowo' },
    { id: 3, name: 'Brzeźno' },
    { id: 4, name: 'Chełm' },
    { id: 5, name: 'Jasień' },
    { id: 6, name: 'Kokoszki' },
    { id: 7, name: 'Krakowiec- Górki Zachodnie' },
    { id: 8, name: 'Letnica' },
    { id: 9, name: 'Matarnia' },
    { id: 10, name: 'Młyniska' },
    { id: 11, name: 'Nowy Port' },
    { id: 12, name: 'Oliwa' },
    { id: 13, name: 'Olszynka' },
    { id: 14, name: 'Orunia Górna-Gdańsk Południe' },
    { id: 15, name: 'Orunia-Św. Wojciech-Lipce' },
    { id: 16, name: 'Osowa' },
    { id: 17, name: 'Piecki- Migowo' },
    { id: 18, name: 'Przeróbka' },
    { id: 19, name: 'Przymorze Małe' },
    { id: 20, name: 'Przymorze Wielkie' },
    { id: 21, name: 'Rudniki' },
    { id: 22, name: 'Siedlce' },
    { id: 23, name: 'Stogi' },
    { id: 24, name: 'Strzyża' },
    { id: 25, name: 'Suchanino' },
    { id: 26, name: 'Śródmieście' },
    { id: 27, name: 'Ujeścisko-Łostowice' },
    { id: 28, name: 'VII Dwór' },
    { id: 29, name: 'Wrzeszcz Dolny' },
    { id: 30, name: 'Wrzeszcz Górny' },
    { id: 31, name: 'Wyspa Sobieszewska' },
    { id: 32, name: 'Wzgórze Mickiewicza' },
    { id: 33, name: 'Zaspa Młyniec' },
    { id: 34, name: 'Zaspa Rozstaje' },
    { id: 35, name: 'Żabianka-Wejhera-Jelit.Tysiąc.' },
  ];
}
